language: ruby
sudo: required
services:
  - docker
script:
  - docker build -t $REPO .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u=exorath -p="$DOCKER_PASSWORD";
    docker push exorath/playersservice;
    fi