apiVersion: v1
kind: Service
metadata:
  name: playersservice
  labels:
    app: playersservice
spec:
  ports:
    - port: 8080
  selector:
    app: playersservice
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: playersservice
  labels:
    app: playersservice
spec:
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: playersservice
    spec:
      containers:
      - name: playersservice
        image: exorath/playersservice
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: AWS_REGION
          value: "EU_CENTRAL_1"
        - name: AWS_ACCESS_KEY_ID
          value: ""
        - name: AWS_SECRET_KEY
          value: "servers"
        - name: TABLE_NAME
          value: "exorath_playersservice"